title = 'Giovanni Geraci'
baseURL = 'https://giovannigeraci.com/'
languageCode = 'en'
defaultContentLanguage = 'en'
theme = 'gokarna'
enableEmoji = true
enableRobotsTXT = true

[params]
footer = "Giovanni Geraci"

description = "hi, i'm giovanni, welcome to my website :-)"
avatarURL = "/images/avatar.jpeg"
AvatarAltText = "avatar"
avatarSize = "size-m"
ShowBackToTopButton = true

socialIcons = [
  {name = "linkedin", url = "https://linkedin.com/in/giovannigeraci"},
  {name = "email", url = "mailto:giovanni@giovannigeraci.com"},
  {name = "github", url = "https://github.com/geragio"},
  {name = "telegram", url = "https://t.me/ggeraci"}
]

[menu]

  [[menu.main]]
  
    identifier = "about"
    url = "/about/"
    pre = ""
    post = ""
    name = "About"
    weight = 1

#   [[menu.main]]
#  
#     identifier = "posts"
#     url = "/blog/"
#     pre = ""
#     post = ""
#     name = "Blog"
#     weight = 2
