title = 'Giovanni Geraci'
baseURL = 'https://giovannigeraci.com/'
languageCode = 'en'
defaultContentLanguage = 'en'
theme = 'gokarna'
enableEmoji = true
enableRobotsTXT = true

[params]
footer = "Giovanni Geraci"

description = "hi, i'm giovanni, welcome to my website :-)"
avatarURL = "/images/avatar.jpeg"
AvatarAltText = "avatar"
avatarSize = "size-xs"
ShowBackToTopButton = true

socialIcons = [
  {name = "linkedin", url = "https://linkedin.com/in/giovannigeraci"},
  {name = "email", url = "mailto:giovanni@giovannigeraci.com"},
  {name = "github", url= "https://github.com/geragio"}
]

[menu]
  [[menu.main]]
  
    identifier = "about"

    url = "/about/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "About"

    # Weights are used to determine the ordering
    weight = 2

  # [[menu.main]]
  
  #   identifier = "posts"

  #   url = "/blog/"
    
  #   # You can add extra information before the name (HTML format is supported), such as icons
  #   pre = ""

  #   # You can add extra information after the name (HTML format is supported), such as icons
  #   post = ""

  #   # Display name
  #   name = "Blog"

  #   # Weights are used to determine the ordering
  #   weight = 1

